project_id = "zdtuvslyqayjedjsfvwa"

[functions.send-telegram-order]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.create-pedido]
verify_jwt = false

[functions.seed-balcao-users]
verify_jwt = false

[functions.chat-admin]
verify_jwt = false